version: 2
updates:

  - package-ecosystem: 'gradle'
    directory: '/SpringCRUD'
    schedule:
      interval: 'daily'
      
  - package-ecosystem: "npm"
    directory: "/AngularCRUD"
    schedule:
      interval: "daily"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
