replicaCount: 2

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

containerPort: 3306

service:
  port: 3306

secrets:
  name: mysql-secrets

persistence:
  enabled: true
  mountPath: /var/lib/mysql
  accessMode: ReadWriteOnce
  size: 10Gi
