apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adminer
  labels:
    app: adminer
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: adminer
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
