apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-akv
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""   # empty = system-assigned identity
    keyvaultName: tierappkv
    tenantId: 31af079b-a6ec-4e36-96a1-741c3fdb3c5d
    objects: |
      array:
        - |
          objectName: mysql-root-password
          objectType: secret
        - |
          objectName: mysql-database
          objectType: secret
        - |
          objectName: mysql-user
          objectType: secret
        - |
          objectName: mysql-password
          objectType: secret

  secretObjects:
  - secretName: mysql-akv
    type: Opaque
    data:
      - objectName: mysql-root-password
        key: MYSQL_ROOT_PASSWORD
      - objectName: mysql-database
        key: MYSQL_DATABASE
      - objectName: mysql-user
        key: MYSQL_USER
      - objectName: mysql-password
        key: MYSQL_PASSWORD

