name: Build & Push MyBookCollection Images

on:
  push:
    branches:
      - feature/test
  pull_request:
    branches:
      - feature/test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./SpringCRUD
          push: true
          tags: |
            sarocky/3tier-backend:latest
            sarocky/3tier-backend:${{ github.sha }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./AngularCRUD
          push: true
          tags: |
            sarocky/3tier-frontend:latest
            sarocky/3tier-frontend:${{ github.sha }}
